server.port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: audit-service
          uri: http://localhost:8889
          predicates:
            - Path=/api/audit/**
          filters:
            - StripPrefix=1